defaults:
  - /slam: low_memory

instance: vipe.pipeline.default.DefaultAnnotationPipeline

# Init configs
init:
  camera_type: "pinhole"
  intrinsics: "geocalib"
  instance:
    kf_gap_sec: 4.0  # Increased keyframe gap to reduce processing load
    phrases: 
      - person
      - animal
      - vehicle
    add_sky: false  # Disable sky detection to save memory

slam:
  keyframe_depth: metric3d-small  # Use smaller depth model
  optimize_intrinsics: ${neq:${..init.intrinsics},"gt"}

# Post-processing configs
post:
  depth_align_model: "adaptive_unidepth-l_svda"

# Output configs
output:
  # Path to save results
  path: vipe_results/
  skip_exists: false

  # Save artifacts and a info file
  save_artifacts: false

  # Enable minimal visualization
  save_viz: true
  viz_downsample: 4
  viz_attributes: [['rgb', 'instance'], ['depth', 'pcd']]